title: StudyVault
description: A platform to learn various subjects through online courses.
baseurl: ""
url: "https://itzneel05.github.io/studyvault"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - README.md
  - .gitignore
  - package.json
  - .github
  - assets
  - src
  - 404.html
  - CNAME